export interface Token {
  id?: string;
  address: string;
  name: string;
  symbol: string;
  description: string;
  imageUrl: string;
  creator: string;
  website: string;
  twitter: string;
  telegram: string;
  totalSupply: string;
  phase: 'CREATED' | 'CURVE' | 'GRADUATING' | 'GRADUATED';
  okbCollected: string;
  tokensTraded: string;
  graduationProgress: number;
  currentPrice: string;
  marketCap: string;
  fdv: string;
  volume24h: string;
  priceChange24h: string;
  curveTradingActive: boolean;
  graduatedAt: string | null;
  izumiPoolAddress: string;
  holderCount: number;
  transactionCount: number;
  isVerified: boolean;
  isFeatured: boolean;
  createdAt: string;
  updatedAt: string;
  network: string;
  isActive: boolean;
}
